export const sectorList = [
  { name: "Bank", tag: "bank" },
  { name: "Cement", tag: "cement" },
  { name: "Ceramics Sector", tag: "ceramics" },
  { name: "Corporate Bond", tag: "corporate" },
  { name: "Debenture", tag: "debenture" },
  { name: "Engineering", tag: "engineering" },
  { name: "Financial Institutions", tag: "financial" },
  { name: "Food & Allied", tag: "food" },
  { name: "Fuel & Power", tag: "fuel" },
  { name: "G-SEC (T.Bond)", tag: "g-sec" },
  { name: "Insurance", tag: "insurance" },
  { name: "IT Sector", tag: "it" },
  { name: "Jute", tag: "jute" },
  { name: "Miscellaneous", tag: "miscellaneous" },
  { name: "Mutual Funds", tag: "mutual" },
  { name: "Paper & Printing", tag: "paper" },
  { name: "Pharmaceuticals & Chemicals", tag: "pharmaceuticals" },
  { name: "Services & Real Estate", tag: "services" },
  { name: "Tannery Industries", tag: "tannery" },
  { name: "Telecommunication", tag: "telecommunication" },
  { name: "Textile", tag: "textile" },
  { name: "Travel & Leisure", tag: "travel" },
];

export const categoryList = ["A", "B", "N", "Z", "SME"];

export const yearEndMap = [
  {
    yearEnd: "30-Jun",
    q1: "Q1 (Jul-Sep)",
    q2: "Q2 (Oct-Dec)",
    q3: "Q3 (Jan-Mar)",
    q4: "Q4 (Apr-Jun)",
  },
  {
    yearEnd: "31-Dec",
    q1: "Q1 (Jan-Mar)",
    q2: "Q2 (Apr-Jun)",
    q3: "Q3 (Jul-Sep)",
    q4: "Q4 (Oct-Dec)",
  },
  {
    yearEnd: "31-Mar",
    q1: "Q1 (Apr-Jun)",
    q2: "Q2 (Jul-Sep)",
    q3: "Q3 (Oct-Dec)",
    q4: "Q4 (Jan-Mar)",
  },
];

export const stockList = [
  {
    tradingCode: "1JANATAMF",
    companyName: "First Janata Bank Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "1STPRIMFMF",
    companyName: "Prime Finance First Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "AAMRANET",
    companyName: "aamra networks limited",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "AAMRATECH",
    companyName: "aamra technologies limited",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "ABB1STMF",
    companyName: "AB Bank 1st Mutual fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ABBANK",
    companyName: "AB Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "ACFL",
    companyName: "Aman Cotton Fibrous Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "ACI",
    companyName: "ACI  Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "ACIFORMULA",
    companyName: "ACI Formulations Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "ACMELAB",
    companyName: "The ACME Laboratories Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "ACMEPL",
    companyName: "ACME Pesticides Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "ACTIVEFINE",
    companyName: "Active Fine Chemicals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "ADNTEL",
    companyName: "ADN Telecom Limited",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "ADVENT",
    companyName: "Advent Pharma Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "AFCAGRO",
    companyName: "AFC Agro Biotech Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "AFTABAUTO",
    companyName: "Aftab Automobiles Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "AGNISYSL",
    companyName: "Agni Systems Ltd.",
    sector: "IT Sector",
    category: "B",
  },
  {
    tradingCode: "AGRANINS",
    companyName: "Agrani Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "AIBL1STIMF",
    companyName: "AIBL 1st Islamic Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "AIL",
    companyName: "Alif Industries Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "AL-HAJTEX",
    companyName: "Al-Haj Textile Mills Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "ALARABANK",
    companyName: "Al-Arafah Islami Bank Ltd",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "ALIF",
    companyName: "Alif Manufacturing Company Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "ALLTEX",
    companyName: "Alltex Industries Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "AMANFEED",
    companyName: "Aman Feed Limited",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "AMBEEPHA",
    companyName: "Ambee Pharmaceuticals PLC",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "AMCL(PRAN)",
    companyName: "Agricultural Marketing Company Ltd. (Pran)",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "ANLIMAYARN",
    companyName: "Anlimayarn Dyeing Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "ANWARGALV",
    companyName: "Anwar Galvanizing Ltd.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "AOL",
    companyName: "Associated Oxygen Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "APEXFOODS",
    companyName: "Apex Foods Limited",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "APEXFOOT",
    companyName: "Apex Footwear Limited.",
    sector: "Tannery Industries",
    category: "A",
  },
  {
    tradingCode: "APEXSPINN",
    companyName: "Apex Spinning & Knitting Mills Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "APEXTANRY",
    companyName: "Apex Tannery Limited",
    sector: "Tannery Industries",
    category: "A",
  },
  {
    tradingCode: "APOLOISPAT",
    companyName: "Appollo Ispat Complex Limited",
    sector: "Engineering",
    category: "Z",
  },
  {
    tradingCode: "ARAMIT",
    companyName: "Aramit Limited",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "ARAMITCEM",
    companyName: "Aramit Cement Limited",
    sector: "Cement",
    category: "B",
  },
  {
    tradingCode: "ARGONDENIM",
    companyName: "Argon Denims Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "ASIAINS",
    companyName: "Asia Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "ASIAPACINS",
    companyName: "Asia Pacific General Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "ATCSLGF",
    companyName: "Asian Tiger Sandhani Life Growth Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ATLASBANG",
    companyName: "Atlas Bangladesh Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "AZIZPIPES",
    companyName: "Aziz Pipes Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "BANGAS",
    companyName: "Bangas Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "BANKASIA",
    companyName: "Bank Asia Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "BARKAPOWER",
    companyName: "Baraka Power Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "BATASHOE",
    companyName: "Bata Shoe Company (Bangladesh) Limited",
    sector: "Tannery Industries",
    category: "A",
  },
  {
    tradingCode: "BATBC",
    companyName: "British American Tobacco Bangladesh Company Limited",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "BAYLEASING",
    companyName: "Bay Leasing & Investment Limited",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "BBS",
    companyName: "Bangladesh Building Systems Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "BBSCABLES",
    companyName: "BBS Cables Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "BDAUTOCA",
    companyName: "Bangladesh Autocars Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "BDCOM",
    companyName: "BDCOM Online Ltd.",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "BDFINANCE",
    companyName: "Bangladesh Finance Limited",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "BDLAMPS",
    companyName: "Bangladesh Lamps Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "BDSERVICE",
    companyName: "Bangladesh Services Ltd.",
    sector: "Travel & Leisure",
    category: "Z",
  },
  {
    tradingCode: "BDTHAI",
    companyName: "Bd.Thai Aluminium Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "BDTHAIFOOD",
    companyName: "BD Thai Food & Beverage Limited",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "BDWELDING",
    companyName: "Bangladesh Welding Electrodes Ltd.",
    sector: "Fuel & Power",
    category: "Z",
  },
  {
    tradingCode: "BEACHHATCH",
    companyName: "Beach Hatchery Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "BEACONPHAR",
    companyName: "Beacon Pharmaceuticals PLC",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "BENGALWTL",
    companyName: "Bengal Windsor Thermoplastics Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "BERGERPBL",
    companyName: "Berger Paints Bangladesh Ltd.",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "BEXIMCO",
    companyName: "Bangladesh Export Import Company Ltd.",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "BGIC",
    companyName: "Bangladesh General Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "BIFC",
    companyName: "Bangladesh Industrial Fin. Co. Ltd.",
    sector: "Financial Institutions",
    category: "Z",
  },
  {
    tradingCode: "BNICL",
    companyName: "Bangladesh National Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "BPML",
    companyName: "Bashundhara Paper Mills Limited",
    sector: "Paper & Printing",
    category: "A",
  },
  {
    tradingCode: "BPPL",
    companyName: "Baraka Patenga Power Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "BRACBANK",
    companyName: "BRAC Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "BSC",
    companyName: "Bangladesh Shipping Corporation",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "BSCCL",
    companyName: "Bangladesh Submarine Cable Company Limited",
    sector: "Telecommunication",
    category: "A",
  },
  {
    tradingCode: "BSRMLTD",
    companyName: "Bangladesh Steel Re-Rolling Mills Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "BSRMSTEEL",
    companyName: "BSRM Steels Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "BXPHARMA",
    companyName: "Beximco Pharmaceuticals Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "BXSYNTH",
    companyName: "Beximco Synthetics Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "Z",
  },
  {
    tradingCode: "CAPMBDBLMF",
    companyName: "CAPM BDBL Mutual Fund 01",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "CAPMIBBLMF",
    companyName: "CAPM IBBL Islamic Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "CENTRALINS",
    companyName: "Central Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "CENTRALPHL",
    companyName: "Central Pharmaceuticals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "CITYBANK",
    companyName: "The City Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "CITYGENINS",
    companyName: "City General Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "CLICL",
    companyName: "Chartered Life Insurance Company Limited",
    sector: "Insurance",
    category: "N",
  },
  {
    tradingCode: "CNATEX",
    companyName: "C & A Textiles Limited",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "CONFIDCEM",
    companyName: "Confidence Cement PLC.",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "CONTININS",
    companyName: "Continental Insurance Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "COPPERTECH",
    companyName: "Coppertech Industries Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "CROWNCEMNT",
    companyName: "Crown Cement PLC.",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "CRYSTALINS",
    companyName: "Crystal Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "CVOPRL",
    companyName: "CVO Petrochemical Refinery Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "DACCADYE",
    companyName: "The Dacca Dyeing & Manufacturing Co.Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "DAFODILCOM",
    companyName: "Daffodil Computers Ltd.",
    sector: "IT Sector",
    category: "B",
  },
  {
    tradingCode: "DBH",
    companyName: "DBH Finance PLC.",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "DBH1STMF",
    companyName: "DBH First Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "DELTALIFE",
    companyName: "Delta Life Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "DELTASPINN",
    companyName: "Delta Spinners Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "DESCO",
    companyName: "Dhaka Electric Supply Company Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "DESHBANDHU",
    companyName: "Deshbandhu Polymer Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "DGIC",
    companyName: "Desh General Insurance Company Limited",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "DHAKABANK",
    companyName: "Dhaka Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "DHAKAINS",
    companyName: "Dhaka Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "DOMINAGE",
    companyName: "Dominage Steel Building Systems Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "DOREENPWR",
    companyName: "Doreen Power Generations and Systems Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "DSHGARME",
    companyName: "Desh Garments Ltd.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "DSSL",
    companyName: "Dragon Sweater and Spinning Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "DULAMIACOT",
    companyName: "Dulamia Cotton Spinning Mills Ltd.",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "DUTCHBANGL",
    companyName: "Dutch-Bangla Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "EASTERNINS",
    companyName: "Eastern Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "EASTLAND",
    companyName: "Eastland Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "EASTRNLUB",
    companyName: "Eastern Lubricants Blenders Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "EBL",
    companyName: "Eastern Bank PLC.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "EBL1STMF",
    companyName: "EBL First Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "EBLNRBMF",
    companyName: "EBL NRB Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ECABLES",
    companyName: "Eastern Cables Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "EGEN",
    companyName: "eGeneration Limited",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "EHL",
    companyName: "Eastern Housing Limited",
    sector: "Services & Real Estate",
    category: "A",
  },
  {
    tradingCode: "EIL",
    companyName: "Express Insurance Limited",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "EMERALDOIL",
    companyName: "Emerald Oil Industries Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "ENVOYTEX",
    companyName: "Envoy Textiles Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "EPGL",
    companyName: "Energypac Power Generation PLC.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "ESQUIRENIT",
    companyName: "Esquire Knit Composite PLC",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "ETL",
    companyName: "Evince Textiles Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "EXIM1STMF",
    companyName: "EXIM Bank 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "EXIMBANK",
    companyName: "Export Import (Exim) Bank of Bangladesh Limited",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "FAMILYTEX",
    companyName: "Familytex (BD) Limited",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "FARCHEM",
    companyName: "Far Chemical Industries Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "FAREASTFIN",
    companyName: "Fareast Finance & Investment Limited",
    sector: "Financial Institutions",
    category: "Z",
  },
  {
    tradingCode: "FAREASTLIF",
    companyName: "Fareast Islami Life Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "FASFIN",
    companyName: "FAS Finance & Investment Limited",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "FBFIF",
    companyName: "First Bangladesh Fixed Income Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "FEDERALINS",
    companyName: "Federal Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "FEKDIL",
    companyName: "Far East Knitting & Dyeing Industries Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "FINEFOODS",
    companyName: "Fine Foods Limited",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "FIRSTFIN",
    companyName: "First Finance Limited",
    sector: "Financial Institutions",
    category: "Z",
  },
  {
    tradingCode: "FIRSTSBANK",
    companyName: "First Security Islami Bank Limited",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "FORTUNE",
    companyName: "Fortune Shoes Limited",
    sector: "Tannery Industries",
    category: "A",
  },
  {
    tradingCode: "FUWANGCER",
    companyName: "Fu-Wang Ceramic Industries Ltd.",
    sector: "Ceramics Sector",
    category: "B",
  },
  {
    tradingCode: "FUWANGFOOD",
    companyName: "Fu Wang Food Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "GBBPOWER",
    companyName: "GBB Power Ltd.",
    sector: "Fuel & Power",
    category: "B",
  },
  {
    tradingCode: "GEMINISEA",
    companyName: "Gemini Sea Food PLC",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "GENEXIL",
    companyName: "Genex Infosys Limited",
    sector: "IT Sector",
    category: "A",
  },
  {
    tradingCode: "GENNEXT",
    companyName: "Generation Next Fashions Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "GHAIL",
    companyName: "Golden Harvest Agro Industries Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "GHCL",
    companyName: "Global Heavy Chemicals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "GIB",
    companyName: "Global Islami Bank PLC",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "GLDNJMF",
    companyName: "ICB AMCL CMSF Golden Jubilee Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "GLOBALINS",
    companyName: "Global Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "GOLDENSON",
    companyName: "Golden Son Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "GP",
    companyName: "Grameenphone Ltd.",
    sector: "Telecommunication",
    category: "A",
  },
  {
    tradingCode: "GPHISPAT",
    companyName: "GPH Ispat Ltd.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "GQBALLPEN",
    companyName: "GQ Ball Pen Industries Ltd.",
    sector: "Miscellaneous",
    category: "B",
  },
  {
    tradingCode: "GRAMEENS2",
    companyName: "Grameen One : Scheme Two",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "GREENDELMF",
    companyName: "Green Delta Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "GREENDELT",
    companyName: "Green Delta Insurance Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "GSPFINANCE",
    companyName: "GSP Finance Company (Bangladesh) Limited",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "HAKKANIPUL",
    companyName: "Hakkani Pulp & Paper Mills Ltd.",
    sector: "Paper & Printing",
    category: "B",
  },
  {
    tradingCode: "HEIDELBCEM",
    companyName: "Heidelberg Cement Bangladesh Ltd.",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "HFL",
    companyName: "Hamid Fabrics Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "HRTEX",
    companyName: "H.R.Textile Ltd.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "HWAWELLTEX",
    companyName: "Hwa Well Textiles (BD) PLC.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "IBNSINA",
    companyName: "The IBN SINA  Pharmaceutical Industry PLC",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "IBP",
    companyName: "Indo-Bangla Pharmaceuticals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "ICB",
    companyName: "Investment Corporation Of Bangladesh",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "ICB3RDNRB",
    companyName: "ICB AMCL Third NRB Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ICBAGRANI1",
    companyName: "ICB AMCL First Agrani Bank Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ICBAMCL2ND",
    companyName: "ICB AMCL Second Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ICBEPMF1S1",
    companyName: "ICB Employees Provident MF 1: Scheme 1",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ICBIBANK",
    companyName: "ICB Islamic Bank Limited",
    sector: "Bank",
    category: "Z",
  },
  {
    tradingCode: "ICBSONALI1",
    companyName: "ICB AMCL Sonali Bank Limited 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ICICL",
    companyName: "Islami Commercial Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "IDLC",
    companyName: "IDLC Finance Ltd.",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "IFADAUTOS",
    companyName: "IFAD Autos Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "IFIC",
    companyName: "IFIC Bank PLC",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "IFIC1STMF",
    companyName: "IFIC Bank 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "IFILISLMF1",
    companyName: "IFIL Islamic Mutual Fund-1",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "ILFSL",
    companyName: "International Leasing & Financial Services Ltd.",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "IMAMBUTTON",
    companyName: "Imam Button Industries Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "Z",
  },
  {
    tradingCode: "INDEXAGRO",
    companyName: "Index Agro Industries Limited",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "INTECH",
    companyName: "Intech  Limited",
    sector: "IT Sector",
    category: "B",
  },
  {
    tradingCode: "INTRACO",
    companyName: "Intraco Refueling Station Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "IPDC",
    companyName: "IPDC Finance Limited",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "ISLAMIBANK",
    companyName: "Islami Bank Bangladesh PLC.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "ISLAMICFIN",
    companyName: "Islamic Finance & Investment Ltd.",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "ISLAMIINS",
    companyName: "Islami Insurance Bangladesh Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "ISNLTD",
    companyName: "Information Services Network Ltd.",
    sector: "IT Sector",
    category: "B",
  },
  {
    tradingCode: "ITC",
    companyName: "IT Consultants Limited",
    sector: "IT Sector",
    category: "B",
  },
  {
    tradingCode: "JAMUNABANK",
    companyName: "Jamuna Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "JAMUNAOIL",
    companyName: "Jamuna Oil Company Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "JANATAINS",
    companyName: "Janata Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "JHRML",
    companyName: "JMI Hospital Requisite Manufacturing Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "JMISMDL",
    companyName: "JMI Syringes & Medical Devices Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "JUTESPINN",
    companyName: "Jute Spinners Ltd.",
    sector: "Jute",
    category: "Z",
  },
  {
    tradingCode: "KARNAPHULI",
    companyName: "Karnaphuli Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "KAY&QUE",
    companyName: "Kay & Que (Bangladesh) Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "KBPPWBIL",
    companyName: "Khan Brothers PP Woven Bag Industries Limited",
    sector: "Miscellaneous",
    category: "B",
  },
  {
    tradingCode: "KDSALTD",
    companyName: "KDS Accessories Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "KEYACOSMET",
    companyName: "Keya Cosmetics Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "KOHINOOR",
    companyName: "Kohinoor Chemicals Company (Bangladesh) Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "KPCL",
    companyName: "Khulna Power Company Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "KPPL",
    companyName: "Khulna Printing & Packaging Limited",
    sector: "Paper & Printing",
    category: "B",
  },
  {
    tradingCode: "KTL",
    companyName: "Kattali Textile Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "LANKABAFIN",
    companyName: "LankaBangla Finance PLC.",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "LEGACYFOOT",
    companyName: "Legacy Footwear Ltd.",
    sector: "Tannery Industries",
    category: "B",
  },
  {
    tradingCode: "LHBL",
    companyName: "LafargeHolcim Bangladesh Limited",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "LIBRAINFU",
    companyName: "Libra Infusions Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "LINDEBD",
    companyName: "Linde Bangladesh Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "LOVELLO",
    companyName: "Taufika Foods and Lovello Ice-cream PLC",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "LRBDL",
    companyName: "Lub-rref (Bangladesh) Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "LRGLOBMF1",
    companyName: "LR Global Bangladesh Mutual Fund One",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "MAKSONSPIN",
    companyName: "Maksons Spinning Mills Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "MALEKSPIN",
    companyName: "Malek Spinning Mills Ltd.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "MARICO",
    companyName: "Marico Bangladesh Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "MATINSPINN",
    companyName: "Matin Spinning Mills PLC",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "MBL1STMF",
    companyName: "MBL 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "MEGCONMILK",
    companyName: "Meghna Condensed Milk Industries Ltd.",
    sector: "Food & Allied",
    category: "Z",
  },
  {
    tradingCode: "MEGHNACEM",
    companyName: "Meghna Cement Mills Ltd.",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "MEGHNAINS",
    companyName: "Meghna Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "MEGHNALIFE",
    companyName: "Meghna Life Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "MEGHNAPET",
    companyName: "Meghna Pet Industries Ltd.",
    sector: "Food & Allied",
    category: "Z",
  },
  {
    tradingCode: "MERCANBANK",
    companyName: "Mercantile Bank PLC.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "MERCINS",
    companyName: "Mercantile Islami Insurance PLC",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "METROSPIN",
    companyName: "Metro Spinning Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "MHSML",
    companyName: "Mozaffar Hossain Spinning Mills Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "MIDASFIN",
    companyName: "MIDAS Financing Ltd.",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "MIDLANDBNK",
    companyName: "Midland Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "MIRACLEIND",
    companyName: "Miracle Industries Ltd.",
    sector: "Miscellaneous",
    category: "B",
  },
  {
    tradingCode: "MIRAKHTER",
    companyName: "Mir Akhter Hossain Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "MITHUNKNIT",
    companyName: "Mithun Knitting and Dyeing Ltd.",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "MJLBD",
    companyName: "MJL Bangladesh PLC.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "MLDYEING",
    companyName: "M.L. Dyeing Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "MONNOAGML",
    companyName: "Monno Agro & General Machinery Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "MONNOCERA",
    companyName: "Monno Ceramic Industries Ltd.",
    sector: "Ceramics Sector",
    category: "A",
  },
  {
    tradingCode: "MONNOFABR",
    companyName: "Monno Fabrics Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "MONOSPOOL",
    companyName: "Bangladesh Monospool Paper Manufacturing Co. Limited",
    sector: "Paper & Printing",
    category: "A",
  },
  {
    tradingCode: "MPETROLEUM",
    companyName: "Meghna Petroleum Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "MTB",
    companyName: "Mutual Trust Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "NAHEEACP",
    companyName: "Nahee Aluminum Composite Panel Ltd.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "NATLIFEINS",
    companyName: "National Life Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "NAVANACNG",
    companyName: "Navana CNG Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "NAVANAPHAR",
    companyName: "Navana Pharmaceuticals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "NBL",
    companyName: "National Bank Ltd.",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "NCCBANK",
    companyName: "National Credit and Commerce Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "NCCBLMF1",
    companyName: "NCCBL Mutual Fund-1",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "NEWLINE",
    companyName: "New Line Clothings Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "NFML",
    companyName: "National Feed Mill Limited",
    sector: "Miscellaneous",
    category: "B",
  },
  {
    tradingCode: "NHFIL",
    companyName: "National Housing Fin. and Inv. Ltd.",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "NITOLINS",
    companyName: "Nitol Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "NORTHERN",
    companyName: "Northern Jute Manufacturing Co. Ltd.",
    sector: "Jute",
    category: "Z",
  },
  {
    tradingCode: "NORTHRNINS",
    companyName: "Northern Islami Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "NPOLYMER",
    companyName: "National Polymer Industries PLC.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "NRBCBANK",
    companyName: "NRBC Bank PLC.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "NTC",
    companyName: "National Tea Company Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "NTLTUBES",
    companyName: "National Tubes Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "NURANI",
    companyName: "Nurani Dyeing & Sweater Limited",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "OAL",
    companyName: "Olympic Accessories Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "OIMEX",
    companyName: "Oimex Electrode Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "OLYMPIC",
    companyName: "Olympic Industries Ltd.",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "ONEBANKLTD",
    companyName: "One Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "ORIONINFU",
    companyName: "Orion Infusion Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "ORIONPHARM",
    companyName: "Orion Pharma Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "PADMALIFE",
    companyName: "Padma Islami Life Insurance Limited",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "PADMAOIL",
    companyName: "Padma Oil Co. Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "PAPERPROC",
    companyName: "Paper Processing & Packaging Limited",
    sector: "Paper & Printing",
    category: "B",
  },
  {
    tradingCode: "PARAMOUNT",
    companyName: "Paramount Insurance Company Ltd.",
    sector: "Insurance",
    category: "-",
  },
  {
    tradingCode: "PDL",
    companyName: "Pacific Denims Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "PENINSULA",
    companyName: "The Peninsula Chittagong Limited",
    sector: "Travel & Leisure",
    category: "B",
  },
  {
    tradingCode: "PEOPLESINS",
    companyName: "Peoples Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PF1STMF",
    companyName: "Phoenix Finance 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "PHARMAID",
    companyName: "Pharma Aids",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "PHENIXINS",
    companyName: "Phoenix Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PHOENIXFIN",
    companyName: "Phoenix Finance and Investments Ltd.",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "PHPMF1",
    companyName: "PHP First Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "PIONEERINS",
    companyName: "Pioneer Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PLFSL",
    companyName: "Peoples Leasing and Fin. Services Ltd.",
    sector: "Financial Institutions",
    category: "Z",
  },
  {
    tradingCode: "POPULAR1MF",
    companyName: "Popular Life First Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "POPULARLIF",
    companyName: "Popular Life Insurance Co. Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "POWERGRID",
    companyName: "Power Grid Company of Bangladesh Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "PRAGATIINS",
    companyName: "Pragati Insurance Ltd",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PRAGATILIF",
    companyName: "Pragati Life Insurance Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PREMIERBAN",
    companyName: "Premier Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "PREMIERCEM",
    companyName: "Premier Cement Mills PLC",
    sector: "Cement",
    category: "A",
  },
  {
    tradingCode: "PREMIERLEA",
    companyName: "Premier Leasing & Finance Limited",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "PRIME1ICBA",
    companyName: "Prime Bank 1st ICB AMCL Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "PRIMEBANK",
    companyName: "Prime Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "PRIMEFIN",
    companyName: "Prime Finance & Investment Ltd.",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "PRIMEINSUR",
    companyName: "Prime Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PRIMELIFE",
    companyName: "Prime Islami Life Insurance Ltd.",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "PRIMETEX",
    companyName: "Prime Textile Spinning Mills Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "PROGRESLIF",
    companyName: "Progressive Life Insurance Co. Ltd.",
    sector: "Insurance",
    category: "Z",
  },
  {
    tradingCode: "PROVATIINS",
    companyName: "Provati Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "PTL",
    companyName: "Paramount Textile PLC.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "PUBALIBANK",
    companyName: "Pubali Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "PURABIGEN",
    companyName: "Purabi Gen. Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "QUASEMIND",
    companyName: "Quasem Industries Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "QUEENSOUTH",
    companyName: "Queen South Textile Mills Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "RAHIMAFOOD",
    companyName: "Rahima Food Corporation Limited",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "RAHIMTEXT",
    companyName: "Rahim Textile Mills Ltd.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "RAKCERAMIC",
    companyName: "RAK Ceramics (Bangladesh) Limited",
    sector: "Ceramics Sector",
    category: "A",
  },
  {
    tradingCode: "RANFOUNDRY",
    companyName: "Rangpur Foundry Ltd.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "RDFOOD",
    companyName: "Rangpur Dairy & Food Products Ltd.",
    sector: "Food & Allied",
    category: "B",
  },
  {
    tradingCode: "RECKITTBEN",
    companyName: "Reckitt Benckiser (Bangladesh) PLC",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "REGENTTEX",
    companyName: "Regent Textile Mills Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "RELIANCE1",
    companyName:
      "Reliance One the first scheme of Reliance Insurance Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "RELIANCINS",
    companyName: "Reliance Insurance Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "RENATA",
    companyName: "Renata Ltd.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "RENWICKJA",
    companyName: "Renwick Jajneswar & Co (Bd) Ltd.",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "REPUBLIC",
    companyName: "Republic Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "RINGSHINE",
    companyName: "Ring Shine Textiles Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "RNSPIN",
    companyName: "R.N. Spinning Mills Limited",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "ROBI",
    companyName: "Robi Axiata Limited",
    sector: "Telecommunication",
    category: "B",
  },
  {
    tradingCode: "RSRMSTEEL",
    companyName: "Ratanpur Steel Re-Rolling Mills Limited",
    sector: "Engineering",
    category: "Z",
  },
  {
    tradingCode: "RUNNERAUTO",
    companyName: "Runner Automobiles PLC",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "RUPALIBANK",
    companyName: "Rupali Bank Ltd.",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "RUPALIINS",
    companyName: "Rupali Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "RUPALILIFE",
    companyName: "Rupali Life Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "SAFKOSPINN",
    companyName: "Safko Spinnings Mills Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "SAIFPOWER",
    companyName: "SAIF Powertec Limited",
    sector: "Services & Real Estate",
    category: "A",
  },
  {
    tradingCode: "SAIHAMCOT",
    companyName: "Saiham Cotton Mills Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "SAIHAMTEX",
    companyName: "Saiham Textile Mills Ltd.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "SALAMCRST",
    companyName: "S. Alam Cold Rolled Steels Ltd.",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "SALVOCHEM",
    companyName: "Salvo Chemical Industry Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "SAMATALETH",
    companyName: "Samata Leather Complex Ltd.",
    sector: "Tannery Industries",
    category: "B",
  },
  {
    tradingCode: "SAMORITA",
    companyName: "Samorita Hospital Limited",
    sector: "Services & Real Estate",
    category: "A",
  },
  {
    tradingCode: "SANDHANINS",
    companyName: "Sandhani Life Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "SAPORTL",
    companyName: "Summit Alliance Port Limited",
    sector: "Services & Real Estate",
    category: "A",
  },
  {
    tradingCode: "SAVAREFR",
    companyName: "Savar Refractories Limited",
    sector: "Miscellaneous",
    category: "Z",
  },
  {
    tradingCode: "SBACBANK",
    companyName: "South Bangla Agriculture & Commerce Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "SEAPEARL",
    companyName: "Sea Pearl Beach Resort & Spa Limited",
    sector: "Travel & Leisure",
    category: "A",
  },
  {
    tradingCode: "SEMLFBSLGF",
    companyName: "SEML FBLSL Growth Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "SEMLIBBLSF",
    companyName: "SEML IBBL Shariah Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "SEMLLECMF",
    companyName: "SEML Lecture Equity Management Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "SHAHJABANK",
    companyName: "Shahjalal Islami Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "SHASHADNIM",
    companyName: "Shasha Denims Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "SHEPHERD",
    companyName: "Shepherd Industries PLC",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "SHURWID",
    companyName: "Shurwid Industries Limited",
    sector: "Engineering",
    category: "Z",
  },
  {
    tradingCode: "SHYAMPSUG",
    companyName: "Shyampur Sugar Mills Ltd.",
    sector: "Food & Allied",
    category: "Z",
  },
  {
    tradingCode: "SIBL",
    companyName: "Social Islami Bank Limited",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "SILCOPHL",
    companyName: "Silco Pharmaceuticals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "SILVAPHL",
    companyName: "Silva Pharmaceuticals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "B",
  },
  {
    tradingCode: "SIMTEX",
    companyName: "Simtex Industries Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "SINGERBD",
    companyName: "Singer Bangladesh Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "SINOBANGLA",
    companyName: "Sinobangla Industries Ltd.",
    sector: "Miscellaneous",
    category: "A",
  },
  {
    tradingCode: "SKICL",
    companyName: "Sena Kalyan Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "SKTRIMS",
    companyName: "SK Trims & Industries Limited",
    sector: "Miscellaneous",
    category: "B",
  },
  {
    tradingCode: "SONALIANSH",
    companyName: "Sonali Aansh Industries Limited",
    sector: "Jute",
    category: "A",
  },
  {
    tradingCode: "SONALILIFE",
    companyName: "Sonali Life Insurance Company Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "SONALIPAPR",
    companyName: "Sonali Paper & Board Mills Ltd.",
    sector: "Paper & Printing",
    category: "A",
  },
  {
    tradingCode: "SONARBAINS",
    companyName: "Sonar Bangla Insurance Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "SONARGAON",
    companyName: "Sonargaon Textiles Ltd.",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "SOUTHEASTB",
    companyName: "Southeast Bank Ltd.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "SPCERAMICS",
    companyName: "Shinepukur Ceramics Limited",
    sector: "Ceramics Sector",
    category: "B",
  },
  {
    tradingCode: "SPCL",
    companyName: "Shahjibazar Power Co. Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "SQUARETEXT",
    companyName: "Square Textiles PLC.",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "SQURPHARMA",
    companyName: "Square Pharmaceuticals PLC.",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "SSSTEEL",
    companyName: "S. S. Steel Limited",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "STANCERAM",
    companyName: "Standard Ceramic Industries Ltd.",
    sector: "Ceramics Sector",
    category: "B",
  },
  {
    tradingCode: "STANDARINS",
    companyName: "Standard Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "STANDBANKL",
    companyName: "Standard Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "STYLECRAFT",
    companyName: "Stylecraft Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "SUMITPOWER",
    companyName: "Summit Power Limited",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "SUNLIFEINS",
    companyName: "Sunlife Insurance Company Limited",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "TAKAFULINS",
    companyName: "Takaful Islami Insurance Limited",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "TALLUSPIN",
    companyName: "Tallu Spinning Mills Ltd.",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "TAMIJTEX",
    companyName: "Tamijuddin Textile Mills PLC",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "TILIL",
    companyName: "Trust Islami Life Insurance Limited",
    sector: "Insurance",
    category: "N",
  },
  {
    tradingCode: "TITASGAS",
    companyName: "Titas Gas Transmission & Dist. Co. Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "TOSRIFA",
    companyName: "Tosrifa Industries Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "TRUSTB1MF",
    companyName: "Trust Bank 1st Mutual Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "TRUSTBANK",
    companyName: "Trust Bank Limited",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "TUNGHAI",
    companyName: "Tung Hai Knitting & Dyeing Limited",
    sector: "Textile",
    category: "Z",
  },
  {
    tradingCode: "UCB",
    companyName: "United Commercial Bank PLC",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "UNILEVERCL",
    companyName: "Unilever Consumer Care Limited",
    sector: "Food & Allied",
    category: "A",
  },
  {
    tradingCode: "UNIONBANK",
    companyName: "Union Bank Limited",
    sector: "Bank",
    category: "B",
  },
  {
    tradingCode: "UNIONCAP",
    companyName: "Union Capital Limited",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "UNIONINS",
    companyName: "Union Insurance Company Limited",
    sector: "Insurance",
    category: "B",
  },
  {
    tradingCode: "UNIQUEHRL",
    companyName: "Unique Hotel & Resorts PLC",
    sector: "Travel & Leisure",
    category: "A",
  },
  {
    tradingCode: "UNITEDFIN",
    companyName: "United Finance Limited",
    sector: "Financial Institutions",
    category: "B",
  },
  {
    tradingCode: "UNITEDINS",
    companyName: "United Insurance Company Ltd.",
    sector: "Insurance",
    category: "A",
  },
  {
    tradingCode: "UPGDCL",
    companyName: "United Power Generation & Distribution Company Ltd.",
    sector: "Fuel & Power",
    category: "A",
  },
  {
    tradingCode: "USMANIAGL",
    companyName: "Usmania Glass Sheet Factory Limited",
    sector: "Miscellaneous",
    category: "Z",
  },
  {
    tradingCode: "UTTARABANK",
    companyName: "Uttara Bank PLC.",
    sector: "Bank",
    category: "A",
  },
  {
    tradingCode: "UTTARAFIN",
    companyName: "Uttara Finance and Investments Limited",
    sector: "Financial Institutions",
    category: "A",
  },
  {
    tradingCode: "VAMLBDMF1",
    companyName: "Vanguard AML BD Finance Mutual Fund One",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "VAMLRBBF",
    companyName: "Vanguard AML Rupali Bank Balanced Fund",
    sector: "Mutual Funds",
    category: "A",
  },
  {
    tradingCode: "VFSTDL",
    companyName: "VFS Thread Dyeing Limited",
    sector: "Textile",
    category: "A",
  },
  {
    tradingCode: "WALTONHIL",
    companyName: "Walton Hi-Tech Industries PLC",
    sector: "Engineering",
    category: "A",
  },
  {
    tradingCode: "WATACHEM",
    companyName: "Wata Chemicals Limited",
    sector: "Pharmaceuticals & Chemicals",
    category: "A",
  },
  {
    tradingCode: "WMSHIPYARD",
    companyName: "Western Marine Shipyard Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "YPL",
    companyName: "Yeakin Polymer Limited",
    sector: "Engineering",
    category: "B",
  },
  {
    tradingCode: "ZAHEENSPIN",
    companyName: "Zaheen Spinning Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "ZAHINTEX",
    companyName: "Zahintex Industries Limited",
    sector: "Textile",
    category: "B",
  },
  {
    tradingCode: "ZEALBANGLA",
    companyName: "Zeal Bangla Sugar Mills Ltd.",
    sector: "Food & Allied",
    category: "Z",
  },
];
