/* eslint-disable @next/next/no-page-custom-font */
'use client';
import './globals.css';
import type { Metadata } from 'next';
import ThemeRegistry from './ThemeRegistry';
import Header from './_components/Header';
import store from './_store';
import { Provider } from 'react-redux';
import React, { FC } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <Provider store={store}>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Header />
            {children}
          </ThemeRegistry>
        </Provider>
      </body>
    </html>
  );
}
