export const filterOptions = [
  {
    name: "tradingCode",
    label: "Trading Code",
    desc: "Trading Code",
    unit: "",
    visible: 0,
    columnOrder: 1,
    options: [],
  },
  // {
  //   name: "index",
  //   label: "Index",
  //   desc: "Index",
  //   unit: "",
  //   visible: 1,
  //   columnOrder: 2,
  //   options: [
  //     { type: "default", text: "DSEX", value: "dsex" },
  //     { type: "default", text: "DSE30", value: "dse30" },
  //   ],
  // },
  {
    name: "sector",
    label: "Sector",
    desc: "Sector",
    unit: "",
    visible: 1,
    columnOrder: 2,
    options: [
      { type: "default", text: "Bank", value: "Bank" },
      { type: "default", text: "Cement", value: "Cement" },
      { type: "default", text: "Ceramics Sector", value: "Ceramics Sector" },
      { type: "default", text: "Corporate Bond", value: "Corporate Bond" },
      { type: "default", text: "Debenture", value: "Debenture" },
      { type: "default", text: "Engineering", value: "Engineering" },
      {
        type: "default",
        text: "Financial Institutions",
        value: "Financial Institutions",
      },
      { type: "default", text: "Food & Allied", value: "Food & Allied" },
      { type: "default", text: "Fuel & Power", value: "Fuel & Power" },
      { type: "default", text: "G-SEC (T.Bond)", value: "G-SEC (T.Bond)" },
      { type: "default", text: "Insurance", value: "Insurance" },
      { type: "default", text: "IT Sector", value: "IT Sector" },
      { type: "default", text: "Jute", value: "Jute" },
      { type: "default", text: "Miscellaneous", value: "Miscellaneous" },
      { type: "default", text: "Mutual Funds", value: "Mutual Funds" },
      { type: "default", text: "Paper & Printing", value: "Paper & Printing" },
      {
        type: "default",
        text: "Pharmaceuticals & Chemicals",
        value: "pharmaceuticals",
      },
      { type: "default", text: "Services & Real Estate", value: "services" },
      { type: "default", text: "Tannery Industries", value: "tannery" },
      {
        type: "default",
        text: "Telecommunication",
        value: "telecommunication",
      },
      { type: "default", text: "Textile", value: "textile" },
      { type: "default", text: "Travel & Leisure", value: "travel" },
    ],
  },
  {
    name: "category",
    label: "Category",
    desc: "Category",
    unit: "",
    visible: 1,
    columnOrder: 3,
    options: [
      { type: "default", text: "A", value: "A" },
      { type: "default", text: "B", value: "B" },
      { type: "default", text: "N", value: "N" },
      { type: "default", text: "Z", value: "Z" },
      { type: "default", text: "SME", value: "SME" },
    ],
  },
  {
    name: "ltp",
    label: "Price",
    desc: "Price",
    unit: "BDT",
    visible: 1,
    columnOrder: 101,
    options: [
      { type: "default", value: "null;10", text: "Under 10 BDT" },
      { type: "default", value: "null;15", text: "Under 15 BDT" },
      { type: "default", value: "null;20", text: "Under 20 BDT" },
      { type: "default", value: "null;30", text: "Under 30 BDT" },
      { type: "default", value: "null;40", text: "Under 40 BDT" },
      { type: "default", value: "null;50", text: "Under 50 BDT" },
      { type: "default", value: "null;100", text: "Under 100 BDT" },
      { type: "default", value: "null;200", text: "Under 200 BDT" },
      { type: "default", value: "null;500", text: "Under 500 BDT" },
      { type: "default", value: "null;1000", text: "Under 1000 BDT" },
      { type: "default", value: "10;null", text: "Over 10 BDT" },
      { type: "default", value: "15;null", text: "Over 15 BDT" },
      { type: "default", value: "20;null", text: "Over 20 BDT" },
      { type: "default", value: "30;null", text: "Over 30 BDT" },
      { type: "default", value: "50;null", text: "Over 50 BDT" },
      { type: "default", value: "100;null", text: "Over 100 BDT" },
      { type: "default", value: "200;null", text: "Over 200 BDT" },
      { type: "default", value: "500;null", text: "Over 500 BDT" },
      { type: "default", value: "1000;null", text: "Over 1000 BDT" },
      { type: "default", value: "10;15", text: "10 to 15 BDT" },
      { type: "default", value: "15;20", text: "15 to 20 BDT" },
      { type: "default", value: "20;30", text: "20 to 30 BDT" },
      { type: "default", value: "30;50", text: "30 to 50 BDT" },
      { type: "default", value: "50;100", text: "50 to 100 BDT" },
      { type: "default", value: "100;200", text: "100 to 200 BDT" },
      { type: "default", value: "200;500", text: "200 to 500 BDT" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "volume",
    label: "Volume",
    desc: "Volume",
    unit: "",
    visible: 1,
    columnOrder: 102,
    options: [
      { type: "default", value: "null;50000", text: "Under 50K" },
      { type: "default", value: "null;100000", text: "Under 100K" },
      { type: "default", value: "null;500000", text: "Under 500K" },
      { type: "default", value: "null;750000", text: "Under 750K" },
      { type: "default", value: "null;1000000", text: "Under 1M" },

      { type: "default", value: "0.000001;null", text: "Over 0" },
      { type: "default", value: "50000;null", text: "Over 50K" },
      { type: "default", value: "100000;null", text: "Over 100K" },
      { type: "default", value: "200000;null", text: "Over 200K" },
      { type: "default", value: "300000;null", text: "Over 300K" },
      { type: "default", value: "400000;null", text: "Over 400K" },
      { type: "default", value: "500000;null", text: "Over 500K" },
      { type: "default", value: "750000;null", text: "Over 750K" },
      { type: "default", value: "1000000;null", text: "Over 1M" },
      { type: "default", value: "2000000;null", text: "Over 2M" },
      { type: "default", value: "5000000;null", text: "Over 5M" },
      { type: "default", value: "10000000;null", text: "Over 10M" },
      { type: "default", value: "20000000;null", text: "Over 20M" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "pricePercentChange",
    label: "Price change",
    desc: "Price change 1 day",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "5;null", text: "High (over 5%)" },
      { type: "default", value: "null;1", text: "Under 1%" },
      { type: "default", value: "null;3", text: "Under 3%" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;8", text: "Under 8%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "1;null", text: "Over 1%" },
      { type: "default", value: "3;null", text: "Over 3%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "8;null", text: "Over 8%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  // {
  //   name: "floor",
  //   label: "Floor",
  //   desc: "Floor",
  //   unit: "",
  //   visible: 1,
  //   columnOrder: 3,
  //   options: [
  //     { type: "default", text: "No", value: "no" },
  //     { type: "default", text: "Yes", value: "yes" },
  //   ],
  // },
  {
    name: "marketCap",
    label: "Market capital",
    desc: "Market capital",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "1000000000;null", text: "Over 100 Crore" },
      { type: "default", value: "2000000000;null", text: "Over 200 Crore" },
      { type: "default", value: "5000000000;null", text: "Over 500 Crore" },
      { type: "default", value: "10000000000;null", text: "Over 1000 Crore" },
      { type: "default", value: "20000000000;null", text: "Over 2000 Crore" },

      { type: "default", value: "null;1000000000", text: "Under 100 Crore" },
      { type: "default", value: "null;2000000000", text: "Under 200 Crore" },
      { type: "default", value: "null;5000000000", text: "Under 500 Crore" },
      { type: "default", value: "null;10000000000", text: "Under 1000 Crore" },
      { type: "default", value: "null;20000000000", text: "Under 2000 Crore" },
      {
        type: "custom",
        value: "null;null",
        text: "Custom (Premium only)",
      },
    ],
  },
  {
    name: "paidUpCap",
    label: "Paid-up capital",
    desc: "Paid-up capital",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "10000000;null", text: "Over 1 Crore" },
      { type: "default", value: "20000000;null", text: "Over 2 Crore" },
      { type: "default", value: "50000000;null", text: "Over 5 Crore" },
      { type: "default", value: "100000000;null", text: "Over 10 Crore" },
      { type: "default", value: "500000000;null", text: "Over 50 Crore" },
      { type: "default", value: "1000000000;null", text: "Over 100 Crore" },
      { type: "default", value: "2000000000;null", text: "Over 200 Crore" },
      { type: "default", value: "5000000000;null", text: "Over 500 Crore" },

      { type: "default", value: "null;10000000", text: "Under 1 Crore" },
      { type: "default", value: "null;20000000", text: "Under 2 Crore" },
      { type: "default", value: "null;50000000", text: "Under 5 Crore" },
      { type: "default", value: "null;100000000", text: "Under 10 Crore" },
      { type: "default", value: "null;500000000", text: "Under 50 Crore" },
      { type: "default", value: "null;1000000000", text: "Under 100 Crore" },
      { type: "default", value: "null;2000000000", text: "Under 200 Crore" },
      { type: "default", value: "null;5000000000", text: "Under 500 Crore" },
      {
        type: "custom",
        value: "null;null",
        text: "Custom (Premium only)",
      },
    ],
  },
  {
    name: "totalShares",
    label: "Total Shares",
    desc: "Total Shares",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.1", text: "Under 10 Lakh" },
      { type: "default", value: "null;0.5", text: "Under 50 Lakh" },
      { type: "default", value: "null;1", text: "Under 1 Crore" },
      { type: "default", value: "null;2", text: "Under 2 Crore" },
      { type: "default", value: "null;3", text: "Under 3 Crore" },
      { type: "default", value: "null;5", text: "Under 5 Crore" },
      { type: "default", value: "null;10", text: "Under 10 Crore" },
      { type: "default", value: "null;15", text: "Under 15 Crore" },
      { type: "default", value: "null;20", text: "Under 20 Crore" },
      { type: "default", value: "0.1;null", text: "Over 10 Lakh" },
      { type: "default", value: "0.5;null", text: "Over 50 Lakh" },
      { type: "default", value: "1;null", text: "Over 1 Crore" },
      { type: "default", value: "2;null", text: "Over 2 Crore" },
      { type: "default", value: "3;null", text: "Over 3 Crore" },
      { type: "default", value: "5;null", text: "Over 5 Crore" },
      { type: "default", value: "10;null", text: "Over 10 Crore" },
      { type: "default", value: "15;null", text: "Over 15 Crore" },
      { type: "default", value: "20;null", text: "Over 20 Crore" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "pe",
    label: "P/E ratio",
    desc: "P/E ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "0.000001;15", text: "Low (under 15)" },
      { type: "default", value: "0.000001;null", text: "Profitable (over 0)" },
      { type: "default", value: "50;null", text: "High (over 50)" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;25", text: "Under 25" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;35", text: "Under 35" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "15;null", text: "Over 15" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "25;null", text: "Over 25" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "35;null", text: "Over 35" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "de",
    label: "D/E ratio",
    desc: "D/E ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "null;0.1", text: "Low (under 0.1)" },
      { type: "default", value: "0.5;null", text: "High (over 0.5)" },

      { type: "default", value: "null;0.1", text: "Under 0.1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },
      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "0.1;null", text: "Over 0.1" },
      { type: "default", value: "0.5;null", text: "Over 0.5" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "ps",
    label: "Price/Sales ratio",
    desc: "Price/Sales ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "10;null", text: "High (over 10)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "pbv",
    label: "Price/Bookvalue ratio",
    desc: "Price/Bookvalue ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "5;null", text: "High (over 5)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "pcf",
    label: "Price/Cash flow ratio",
    desc: "Price/Cash flow ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "null;3", text: "Low (under 3)" },
      { type: "default", value: "50;null", text: "High (over 50)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "currentRatio",
    label: "Current ratio",
    desc: "Current ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 103,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "3;null", text: "High (over 3)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },

      { type: "default", value: "0.5;null", text: "Over 0.5" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "1.5;null", text: "Over 1.5" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "roe",
    label: "Return on equity",
    desc: "Return on equity",
    unit: "",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      {
        type: "default",
        value: "null;-15",
        text: "Very Negative (under -15%)",
      },
      { type: "default", value: "30;null", text: "Very Positive (over +30%)" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "null;-30", text: "Under -30%" },
      { type: "default", value: "null;-40", text: "Under -40%" },
      { type: "default", value: "null;-50", text: "Under -50%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "default", value: "30;null", text: "Over +30%" },
      { type: "default", value: "40;null", text: "Over +40%" },
      { type: "default", value: "50;null", text: "Over +50%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "roa",
    label: "Return on assets",
    desc: "Return on assets",
    unit: "",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      {
        type: "default",
        value: "null;-15",
        text: "Very Negative (under -15%)",
      },
      { type: "default", value: "15;null", text: "Very Positive (over +15%)" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "null;-30", text: "Under -30%" },
      { type: "default", value: "null;-40", text: "Under -40%" },
      { type: "default", value: "null;-50", text: "Under -50%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "default", value: "30;null", text: "Over +30%" },
      { type: "default", value: "40;null", text: "Over +40%" },
      { type: "default", value: "50;null", text: "Over +50%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "dividend",
    label: "Dividend type",
    desc: "Dividend type",
    unit: "",
    visible: 1,
    columnOrder: 3,
    options: [
      { type: "default", text: "No dividend", value: "no" },
      { type: "default", text: "Only cash", value: "cashOnly" },
      { type: "default", text: "Only stock", value: "StockOnly" },
      { type: "default", text: "Cash + stock", value: "both" },
    ],
  },
  {
    name: "dividendYield",
    label: "Dividend Yield",
    desc: "Dividend Yield",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;2", text: "Under 2%" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;8", text: "Under 8%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "2;null", text: "Over 2%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "8;null", text: "Over 8%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "cashDividend",
    label: "Cash dividend",
    desc: "Cash dividend",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "stockDividend",
    label: "Stock dividend",
    desc: "Stock dividend",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },

      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "revenueGrowthOneYear",
    label: "Revenue growth 1 year",
    desc: "Revenue growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "revenueGrowthFiveYear",
    label: "Revenue growth 5 year",
    desc: "Revenue growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "epsGrowthOneYear",
    label: "EPS growth 1 year",
    desc: "EPS growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "epsGrowthFiveYear",
    label: "EPS growth 5 year",
    desc: "EPS growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "epsGrowthQuarter",
    label: "EPS growth qtr over qtr",
    desc: "EPS growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "navGrowthOneYear",
    label: "NAV growth 1 year",
    desc: "NAV growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "navGrowthQuarter",
    label: "NAV growth qtr over qtr",
    desc: "NAV growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "nocfpsGrowthOneYear",
    label: "NOCFPS growth 1 year",
    desc: "NOCFPS growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "nocfpsGrowthQuarter",
    label: "NOCFPS growth qtr over qtr",
    desc: "NOCFPS growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "totalAssetGrowthOneYear",
    label: "Total asset growth 1 year",
    desc: "Total asset growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "totalAssetGrowthFiveYear",
    label: "Total asset growth 5 year",
    desc: "Total asset growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "netIncomeGrowthOneYear",
    label: "Net income growth 1 year",
    desc: "Net income growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "netIncomeGrowthFiveYear",
    label: "Net income growth 5 year",
    desc: "Net income growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "totalLiabilitiesGrowthOneYear",
    label: "Total liabilities growth 1 year",
    desc: "Total liabilities growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "operatingProfitGrowthOneYear",
    label: "Operating profit growth 1 year",
    desc: "Operating profit growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "directorShareHolding",
    label: "Director share",
    desc: "Director shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "govtShareHolding",
    label: "Government share",
    desc: "Government shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "publicShareHolding",
    label: "Public share",
    desc: "Public shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "foreignShareHolding",
    label: "Foreign share",
    desc: "Foreign shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "instituteShareHolding",
    label: "Institute share",
    desc: "Institute shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "freeFloatShare",
    label: "Free float share",
    desc: "Free float share (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "0;10", text: "Low (under 50%)" },
      { type: "default", value: "25;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "directorShareHoldingChange",
    label: "Director share change",
    desc: "Director shareholding Change(%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Under -1%" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "1;null", text: "Over +1%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "instituteShareHoldingChange",
    label: "Institute share change",
    desc: "Institute shareholding Change(%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Under -1%" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "1;null", text: "Over +1%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
  {
    name: "reserve",
    label: "Reserve & Surplus",
    desc: "Reserve & Surplus",
    unit: "Crore",
    visible: 1,
    columnOrder: 10,
    options: [
      { type: "default", value: "null;0.1", text: "Under 10 Lakh" },
      { type: "custom", value: "null;null", text: "Custom (Premium only)" },
    ],
  },
];
