export const filterOptions = [
  {
    name: 'tradingCode',
    label: 'Trading Code',
    desc: 'Trading Code',
    unit: '',
    visible: 0,
    columnOrder: 1,
    options: [],
  },
  {
    name: 'sector',
    label: 'Sector',
    desc: 'Sector',
    unit: '',
    visible: 1,
    columnOrder: 2,
    options: [
      { type: 'default', text: 'Bank', value: 'Bank' },
      { type: 'default', text: 'Cement', value: 'Cement' },
      { type: 'default', text: 'Ceramics Sector', value: 'Ceramics Sector' },
      { type: 'default', text: 'Corporate Bond', value: 'Corporate Bond' },
      { type: 'default', text: 'Debenture', value: 'Debenture' },
      { type: 'default', text: 'Engineering', value: 'Engineering' },
      {
        type: 'default',
        text: 'Financial Institutions',
        value: 'Financial Institutions',
      },
      { type: 'default', text: 'Food & Allied', value: 'Food & Allied' },
      { type: 'default', text: 'Fuel & Power', value: 'Fuel & Power' },
      { type: 'default', text: 'G-SEC (T.Bond)', value: 'G-SEC (T.Bond)' },
      { type: 'default', text: 'Insurance', value: 'Insurance' },
      { type: 'default', text: 'IT Sector', value: 'IT Sector' },
      { type: 'default', text: 'Jute', value: 'Jute' },
      { type: 'default', text: 'Miscellaneous', value: 'Miscellaneous' },
      { type: 'default', text: 'Mutual Funds', value: 'Mutual Funds' },
      { type: 'default', text: 'Paper & Printing', value: 'Paper & Printing' },
      {
        type: 'default',
        text: 'Pharmaceuticals & Chemicals',
        value: 'pharmaceuticals',
      },
      { type: 'default', text: 'Services & Real Estate', value: 'services' },
      { type: 'default', text: 'Tannery Industries', value: 'tannery' },
      {
        type: 'default',
        text: 'Telecommunication',
        value: 'telecommunication',
      },
      { type: 'default', text: 'Textile', value: 'textile' },
      { type: 'default', text: 'Travel & Leisure', value: 'travel' },
    ],
  },
  {
    name: 'category',
    label: 'Category',
    desc: 'Category',
    unit: '',
    visible: 1,
    columnOrder: 3,
    options: [
      { type: 'default', text: 'A', value: 'A' },
      { type: 'default', text: 'B', value: 'B' },
      { type: 'default', text: 'N', value: 'N' },
      { type: 'default', text: 'Z', value: 'Z' },
      { type: 'default', text: 'SME', value: 'SME' },
    ],
  },
  {
    name: 'ltp',
    label: 'Price',
    desc: 'Price',
    unit: 'BDT',
    visible: 1,
    columnOrder: 101,
    options: [
      { type: 'default', value: 'null;10', text: 'Under 10 BDT' },
      { type: 'default', value: 'null;15', text: 'Under 15 BDT' },
      { type: 'default', value: 'null;20', text: 'Under 20 BDT' },
      { type: 'default', value: 'null;30', text: 'Under 30 BDT' },
      { type: 'default', value: 'null;40', text: 'Under 40 BDT' },
      { type: 'default', value: 'null;50', text: 'Under 50 BDT' },
      { type: 'default', value: 'null;100', text: 'Under 100 BDT' },
      { type: 'default', value: 'null;200', text: 'Under 200 BDT' },
      { type: 'default', value: 'null;500', text: 'Under 500 BDT' },
      { type: 'default', value: 'null;1000', text: 'Under 1000 BDT' },
      { type: 'default', value: '10;null', text: 'Over 10 BDT' },
      { type: 'default', value: '15;null', text: 'Over 15 BDT' },
      { type: 'default', value: '20;null', text: 'Over 20 BDT' },
      { type: 'default', value: '30;null', text: 'Over 30 BDT' },
      { type: 'default', value: '50;null', text: 'Over 50 BDT' },
      { type: 'default', value: '100;null', text: 'Over 100 BDT' },
      { type: 'default', value: '200;null', text: 'Over 200 BDT' },
      { type: 'default', value: '500;null', text: 'Over 500 BDT' },
      { type: 'default', value: '1000;null', text: 'Over 1000 BDT' },
      { type: 'default', value: '10;15', text: '10 to 15 BDT' },
      { type: 'default', value: '15;20', text: '15 to 20 BDT' },
      { type: 'default', value: '20;30', text: '20 to 30 BDT' },
      { type: 'default', value: '30;50', text: '30 to 50 BDT' },
      { type: 'default', value: '50;100', text: '50 to 100 BDT' },
      { type: 'default', value: '100;200', text: '100 to 200 BDT' },
      { type: 'default', value: '200;500', text: '200 to 500 BDT' },
      { type: 'custom', value: 'null;null', text: 'Custom (Premium only)' },
    ],
  },
  {
    name: 'volume',
    label: 'Volume',
    desc: 'Volume',
    unit: '',
    visible: 1,
    columnOrder: 102,
    options: [],
  },
  {
    name: 'pe',
    label: 'P/E ratio',
    desc: 'P/E ratio',
    unit: 'ratio',
    visible: 1,
    columnOrder: 103,
    options: [
      { type: 'default', value: 'null;15', text: 'Low (under 15)' },
      { type: 'default', value: '0;null', text: 'Profitable (over 0)' },
      { type: 'default', value: '50;null', text: 'High (over 50)' },
      { type: 'default', value: 'null;5', text: 'Under 5' },
      { type: 'default', value: 'null;10', text: 'Under 10' },
      { type: 'default', value: 'null;20', text: 'Under 20' },
      { type: 'default', value: 'null;25', text: 'Under 25' },
      { type: 'default', value: 'null;30', text: 'Under 30' },
      { type: 'default', value: 'null;35', text: 'Under 35' },
      { type: 'default', value: 'null;40', text: 'Under 40' },
      { type: 'default', value: '5;null', text: 'Over 5' },
      { type: 'default', value: '10;null', text: 'Over 10' },
      { type: 'default', value: '15;null', text: 'Over 15' },
      { type: 'default', value: '20;null', text: 'Over 20' },
      { type: 'default', value: '25;null', text: 'Over 25' },
      { type: 'default', value: '30;null', text: 'Over 30' },
      { type: 'default', value: '35;null', text: 'Over 35' },
      { type: 'default', value: '40;null', text: 'Over 40' },
      { type: 'custom', value: 'null;null', text: 'Custom (Premium only)' },
    ],
  },
  {
    name: 'marketCap',
    label: 'Market capital',
    desc: 'Market capital',
    unit: 'Crore',
    visible: 1,
    columnOrder: 10,
    options: [
      { type: 'default', value: 'null;200;10000000', text: 'Below 200 crore' },
      { type: 'default', value: '200;500;10000000', text: '200 to 500 crore' },
      {
        type: 'default',
        value: '500;1000;10000000',
        text: '500 to 1000 crore',
      },
      {
        type: 'default',
        value: '1000;2000;10000000',
        text: '1000 to 2000 crore',
      },
      {
        type: 'default',
        value: '2000;null;10000000',
        text: 'Above 2000 crore',
      },
      {
        type: 'custom',
        value: 'null;null',
        text: 'Custom (Premium only)',
      },
    ],
  },
  {
    name: 'revenueGrowthOneYear',
    label: 'Revenue growth 1 year',
    desc: 'Revenue growth 1 year',
    unit: '%',
    visible: 1,
    columnOrder: 10,
    options: [
      { type: 'default', value: 'null;0', text: 'Negative (under 0)' },
      { type: 'default', value: '0;null', text: 'Positive (over 0)' },
      { type: 'default', value: '0;10', text: 'Positive low (0-10%)' },
      { type: 'default', value: '25;null', text: 'High (over 25%)' },
      { type: 'default', value: 'null;5', text: 'Under 5%' },
      { type: 'default', value: 'null;10', text: 'Under 10%' },
      { type: 'default', value: 'null;15', text: 'Under 15%' },
      { type: 'default', value: 'null;20', text: 'Under 20%' },
      { type: 'default', value: 'null;25', text: 'Under 25%' },
      { type: 'default', value: 'null;30', text: 'Under 30%' },
      { type: 'default', value: '5;null', text: 'Over 5%' },
      { type: 'default', value: '10;null', text: 'Over 10%' },
      { type: 'default', value: '15;null', text: 'Over 15%' },
      { type: 'default', value: '20;null', text: 'Over 20%' },
      { type: 'default', value: '30;null', text: 'Over 30%' },
      { type: 'custom', value: 'null;null', text: 'Custom (Premium only)' },
    ],
  },
];
