export const filterOptions = [
  {
    name: "tradingCode",
    label: "Trading Code",
    desc: "Trading Code",
    unit: "",
    visible: 0,
    columnOrder: 1,
    options: [],
  },
  // {
  //   name: "index",
  //   label: "Index",
  //   desc: "Index",
  //   unit: "",
  //   visible: 1,
  //   columnOrder: 2,
  //   options: [
  //     { type: "default", text: "DSEX", value: "dsex" },
  //     { type: "default", text: "DSE30", value: "dse30" },
  //   ],
  // },
  {
    name: "sector",
    label: "Sector",
    desc: "Sector",
    unit: "",
    visible: 1,
    columnOrder: 2,
    options: [
      { type: "default", text: "Bank", value: "Bank" },
      { type: "default", text: "Cement", value: "Cement" },
      { type: "default", text: "Ceramics Sector", value: "Ceramics Sector" },
      { type: "default", text: "Corporate Bond", value: "Corporate Bond" },
      { type: "default", text: "Debenture", value: "Debenture" },
      { type: "default", text: "Engineering", value: "Engineering" },
      {
        type: "default",
        text: "Financial Institutions",
        value: "Financial Institutions",
      },
      { type: "default", text: "Food & Allied", value: "Food & Allied" },
      { type: "default", text: "Fuel & Power", value: "Fuel & Power" },
      { type: "default", text: "G-SEC (T.Bond)", value: "G-SEC (T.Bond)" },
      { type: "default", text: "Insurance", value: "Insurance" },
      { type: "default", text: "IT Sector", value: "IT Sector" },
      { type: "default", text: "Jute", value: "Jute" },
      { type: "default", text: "Miscellaneous", value: "Miscellaneous" },
      { type: "default", text: "Mutual Funds", value: "Mutual Funds" },
      { type: "default", text: "Paper & Printing", value: "Paper & Printing" },
      {
        type: "default",
        text: "Pharmaceuticals & Chemicals",
        value: "Pharmaceuticals & Chemicals",
      },
      {
        type: "default",
        text: "Services & Real Estate",
        value: "Services & Real Estate",
      },
      {
        type: "default",
        text: "Tannery Industries",
        value: "Tannery Industries",
      },
      {
        type: "default",
        text: "Telecommunication",
        value: "Telecommunication",
      },
      { type: "default", text: "Textile", value: "Textile" },
      { type: "default", text: "Travel & Leisure", value: "Travel & Leisure" },
    ],
  },
  {
    name: "category",
    label: "Category",
    desc: "Category",
    unit: "",
    visible: 1,
    columnOrder: 3,
    options: [
      { type: "default", text: "A", value: "A" },
      { type: "default", text: "B", value: "B" },
      { type: "default", text: "N", value: "N" },
      { type: "default", text: "Z", value: "Z" },
      { type: "default", text: "SME", value: "SME" },
    ],
  },
  {
    name: "ltp",
    label: "Price",
    desc: "Price",
    unit: "BDT",
    visible: 1,
    columnOrder: 1001,
    options: [
      { type: "default", value: "null;10", text: "Under 10 BDT" },
      { type: "default", value: "null;15", text: "Under 15 BDT" },
      { type: "default", value: "null;20", text: "Under 20 BDT" },
      { type: "default", value: "null;30", text: "Under 30 BDT" },
      { type: "default", value: "null;40", text: "Under 40 BDT" },
      { type: "default", value: "null;50", text: "Under 50 BDT" },
      { type: "default", value: "null;100", text: "Under 100 BDT" },
      { type: "default", value: "null;200", text: "Under 200 BDT" },
      { type: "default", value: "null;500", text: "Under 500 BDT" },
      { type: "default", value: "null;1000", text: "Under 1000 BDT" },
      { type: "default", value: "10;null", text: "Over 10 BDT" },
      { type: "default", value: "15;null", text: "Over 15 BDT" },
      { type: "default", value: "20;null", text: "Over 20 BDT" },
      { type: "default", value: "30;null", text: "Over 30 BDT" },
      { type: "default", value: "50;null", text: "Over 50 BDT" },
      { type: "default", value: "100;null", text: "Over 100 BDT" },
      { type: "default", value: "200;null", text: "Over 200 BDT" },
      { type: "default", value: "500;null", text: "Over 500 BDT" },
      { type: "default", value: "1000;null", text: "Over 1000 BDT" },
      { type: "default", value: "10;15", text: "10 to 15 BDT" },
      { type: "default", value: "15;20", text: "15 to 20 BDT" },
      { type: "default", value: "20;30", text: "20 to 30 BDT" },
      { type: "default", value: "30;50", text: "30 to 50 BDT" },
      { type: "default", value: "50;100", text: "50 to 100 BDT" },
      { type: "default", value: "100;200", text: "100 to 200 BDT" },
      { type: "default", value: "200;500", text: "200 to 500 BDT" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "volume",
    label: "Volume",
    desc: "Volume",
    unit: "",
    visible: 1,
    columnOrder: 1003,
    options: [
      { type: "default", value: "null;50000", text: "Under 50K" },
      { type: "default", value: "null;100000", text: "Under 100K" },
      { type: "default", value: "null;500000", text: "Under 500K" },
      { type: "default", value: "null;750000", text: "Under 750K" },
      { type: "default", value: "null;1000000", text: "Under 1M" },
      { type: "default", value: "0.000001;null", text: "Over 0" },
      { type: "default", value: "50000;null", text: "Over 50K" },
      { type: "default", value: "100000;null", text: "Over 100K" },
      { type: "default", value: "200000;null", text: "Over 200K" },
      { type: "default", value: "300000;null", text: "Over 300K" },
      { type: "default", value: "400000;null", text: "Over 400K" },
      { type: "default", value: "500000;null", text: "Over 500K" },
      { type: "default", value: "750000;null", text: "Over 750K" },
      { type: "default", value: "1000000;null", text: "Over 1M" },
      { type: "default", value: "2000000;null", text: "Over 2M" },
      { type: "default", value: "5000000;null", text: "Over 5M" },
      { type: "default", value: "10000000;null", text: "Over 10M" },
      { type: "default", value: "20000000;null", text: "Over 20M" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  // {
  //   name: "floor",
  //   label: "Floor",
  //   desc: "Floor",
  //   unit: "",
  //   visible: 1,
  //   columnOrder: 3,
  //   options: [
  //     { type: "default", text: "No", value: "no" },
  //     { type: "default", text: "Yes", value: "yes" },
  //   ],
  // },
  {
    name: "marketCap",
    label: "Market Capital",
    desc: "Market Capital",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 1005,
    options: [
      { type: "default", value: "100;null", text: "Over 100 Crore" },
      { type: "default", value: "200;null", text: "Over 200 Crore" },
      { type: "default", value: "500;null", text: "Over 500 Crore" },
      { type: "default", value: "1000;null", text: "Over 1000 Crore" },
      { type: "default", value: "2000;null", text: "Over 2000 Crore" },
      { type: "default", value: "null;100", text: "Under 100 Crore" },
      { type: "default", value: "null;200", text: "Under 200 Crore" },
      { type: "default", value: "null;500", text: "Under 500 Crore" },
      { type: "default", value: "null;1000", text: "Under 1000 Crore" },
      { type: "default", value: "null;2000", text: "Under 2000 Crore" },
      {
        type: "custom",
        value: "null;null",
        text: "Custom range",
      },
    ],
  },
  {
    name: "paidUpCap",
    label: "Paidup Capital",
    desc: "Paid-up capital",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "1;null", text: "Over 1 Crore" },
      { type: "default", value: "2;null", text: "Over 2 Crore" },
      { type: "default", value: "5;null", text: "Over 5 Crore" },
      { type: "default", value: "10;null", text: "Over 10 Crore" },
      { type: "default", value: "50;null", text: "Over 50 Crore" },
      { type: "default", value: "100;null", text: "Over 100 Crore" },
      { type: "default", value: "200;null", text: "Over 200 Crore" },
      { type: "default", value: "500;null", text: "Over 500 Crore" },

      { type: "default", value: "null;1", text: "Under 1 Crore" },
      { type: "default", value: "null;2", text: "Under 2 Crore" },
      { type: "default", value: "null;5", text: "Under 5 Crore" },
      { type: "default", value: "null;10", text: "Under 10 Crore" },
      { type: "default", value: "null;50", text: "Under 50 Crore" },
      { type: "default", value: "null;100", text: "Under 100 Crore" },
      { type: "default", value: "null;200", text: "Under 200 Crore" },
      { type: "default", value: "null;500", text: "Under 500 Crore" },
      {
        type: "custom",
        value: "null;null",
        text: "Custom range",
      },
    ],
  },
  {
    name: "authCap",
    label: "Authorized Capital",
    desc: "Authorized Capital",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "1;null", text: "Over 1 Crore" },
      { type: "default", value: "2;null", text: "Over 2 Crore" },
      { type: "default", value: "5;null", text: "Over 5 Crore" },
      { type: "default", value: "10;null", text: "Over 10 Crore" },
      { type: "default", value: "50;null", text: "Over 50 Crore" },
      { type: "default", value: "100;null", text: "Over 100 Crore" },
      { type: "default", value: "200;null", text: "Over 200 Crore" },
      { type: "default", value: "500;null", text: "Over 500 Crore" },

      { type: "default", value: "null;1", text: "Under 1 Crore" },
      { type: "default", value: "null;2", text: "Under 2 Crore" },
      { type: "default", value: "null;5", text: "Under 5 Crore" },
      { type: "default", value: "null;10", text: "Under 10 Crore" },
      { type: "default", value: "null;50", text: "Under 50 Crore" },
      { type: "default", value: "null;100", text: "Under 100 Crore" },
      { type: "default", value: "null;200", text: "Under 200 Crore" },
      { type: "default", value: "null;500", text: "Under 500 Crore" },
      {
        type: "custom",
        value: "null;null",
        text: "Custom range",
      },
    ],
  },
  {
    name: "totalShares",
    label: "Total Shares",
    desc: "Total Shares",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 1006,
    options: [
      { type: "default", value: "null;0.1", text: "Under 10 Lakh" },
      { type: "default", value: "null;0.5", text: "Under 50 Lakh" },
      { type: "default", value: "null;1", text: "Under 1 Crore" },
      { type: "default", value: "null;2", text: "Under 2 Crore" },
      { type: "default", value: "null;3", text: "Under 3 Crore" },
      { type: "default", value: "null;5", text: "Under 5 Crore" },
      { type: "default", value: "null;10", text: "Under 10 Crore" },
      { type: "default", value: "null;15", text: "Under 15 Crore" },
      { type: "default", value: "null;20", text: "Under 20 Crore" },
      { type: "default", value: "0.1;null", text: "Over 10 Lakh" },
      { type: "default", value: "0.5;null", text: "Over 50 Lakh" },
      { type: "default", value: "1;null", text: "Over 1 Crore" },
      { type: "default", value: "2;null", text: "Over 2 Crore" },
      { type: "default", value: "3;null", text: "Over 3 Crore" },
      { type: "default", value: "5;null", text: "Over 5 Crore" },
      { type: "default", value: "10;null", text: "Over 10 Crore" },
      { type: "default", value: "15;null", text: "Over 15 Crore" },
      { type: "default", value: "20;null", text: "Over 20 Crore" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },

  {
    name: "epsCurrent",
    label: "EPS (TTM)",
    desc: "EPS (TTM)",
    unit: "",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },

      { type: "default", value: "null;0.1", text: "Under 0.1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },
      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "navCurrent",
    label: "NAV (current)",
    desc: "NAV (current)",
    unit: "",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },

      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;50", text: "Under 50" },
      { type: "default", value: "null;100", text: "Under 100" },

      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "50;null", text: "Over 50" },
      { type: "default", value: "100;null", text: "Over 100" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "nocfpsCurrent",
    label: "NOCFPS (current)",
    desc: "NOCFPS (current)",
    unit: "",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0)" },

      { type: "default", value: "null;0.1", text: "Under 0.1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },
      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },

  {
    name: "pe",
    label: "P/E ratio",
    desc: "P/E ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 1004,
    options: [
      { type: "default", value: "0.000001;15", text: "Low (under 15)" },
      { type: "default", value: "0.000001;null", text: "Profitable (over 0)" },
      { type: "default", value: "50;null", text: "High (over 50)" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;25", text: "Under 25" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;35", text: "Under 35" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "15;null", text: "Over 15" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "25;null", text: "Over 25" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "35;null", text: "Over 35" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "de",
    label: "D/E ratio",
    desc: "D/E ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;0.1", text: "Low (under 0.1)" },
      { type: "default", value: "0.5;null", text: "High (over 0.5)" },

      { type: "default", value: "null;0.1", text: "Under 0.1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },
      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "0.1;null", text: "Over 0.1" },
      { type: "default", value: "0.5;null", text: "Over 0.5" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "ps",
    label: "Price/Sales ratio",
    desc: "Price/Sales ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "10;null", text: "High (over 10)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pbv",
    label: "Price/Bookvalue ratio",
    desc: "Price/Bookvalue ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "5;null", text: "High (over 5)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pcf",
    label: "Price/Cash flow ratio",
    desc: "Price/Cash flow ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;3", text: "Low (under 3)" },
      { type: "default", value: "50;null", text: "High (over 50)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;4", text: "Under 4" },
      { type: "default", value: "null;5", text: "Under 5" },
      { type: "default", value: "null;6", text: "Under 6" },
      { type: "default", value: "null;7", text: "Under 7" },
      { type: "default", value: "null;8", text: "Under 8" },
      { type: "default", value: "null;9", text: "Under 9" },
      { type: "default", value: "null;10", text: "Under 10" },

      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "currentRatio",
    label: "Current ratio",
    desc: "Current ratio",
    unit: "Ratio",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;1", text: "Low (under 1)" },
      { type: "default", value: "3;null", text: "High (over 3)" },

      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;0.5", text: "Under 0.5" },

      { type: "default", value: "0.5;null", text: "Over 0.5" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "1.5;null", text: "Over 1.5" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "10;null", text: "Over 10" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "roe",
    label: "Return on equity",
    desc: "Return on equity",
    unit: "",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      {
        type: "default",
        value: "null;-15",
        text: "Very Negative (under -15%)",
      },
      { type: "default", value: "30;null", text: "Very Positive (over +30%)" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "null;-30", text: "Under -30%" },
      { type: "default", value: "null;-40", text: "Under -40%" },
      { type: "default", value: "null;-50", text: "Under -50%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "default", value: "30;null", text: "Over +30%" },
      { type: "default", value: "40;null", text: "Over +40%" },
      { type: "default", value: "50;null", text: "Over +50%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "roa",
    label: "Return on assets",
    desc: "Return on assets",
    unit: "",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      {
        type: "default",
        value: "null;-15",
        text: "Very Negative (under -15%)",
      },
      { type: "default", value: "15;null", text: "Very Positive (over +15%)" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "null;-30", text: "Under -30%" },
      { type: "default", value: "null;-40", text: "Under -40%" },
      { type: "default", value: "null;-50", text: "Under -50%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "default", value: "30;null", text: "Over +30%" },
      { type: "default", value: "40;null", text: "Over +40%" },
      { type: "default", value: "50;null", text: "Over +50%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  // {
  //   name: "dividend",
  //   label: "Dividend type",
  //   desc: "Dividend type",
  //   unit: "",
  //   visible: 1,
  //   columnOrder: 3,
  //   options: [
  //     { type: "default", text: "No dividend", value: "no" },
  //     { type: "default", text: "Only cash", value: "cashOnly" },
  //     { type: "default", text: "Only stock", value: "StockOnly" },
  //     { type: "default", text: "Cash + stock", value: "both" },
  //   ],
  // },
  {
    name: "dividendYield",
    label: "Dividend Yield",
    desc: "Dividend Yield",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;2", text: "Under 2%" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;8", text: "Under 8%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "2;null", text: "Over 2%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "8;null", text: "Over 8%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "cashDividend",
    label: "Cash dividend",
    desc: "Cash dividend",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "stockDividend",
    label: "Stock dividend",
    desc: "Stock dividend",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;0.000001", text: "None (0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },

      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },

      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },

      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },

  {
    name: "epsGrowthOneYear",
    label: "EPS growth 1 year",
    desc: "EPS growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "epsGrowthFiveYear",
    label: "EPS growth 5 year",
    desc: "EPS growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "epsGrowthQuarter",
    label: "EPS growth qtr over qtr",
    desc: "EPS growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "navGrowthOneYear",
    label: "NAV growth 1 year",
    desc: "NAV growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "navGrowthQuarter",
    label: "NAV growth qtr over qtr",
    desc: "NAV growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "nocfpsGrowthOneYear",
    label: "NOCFPS growth 1 year",
    desc: "NOCFPS growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "nocfpsGrowthQuarter",
    label: "NOCFPS growth qtr over qtr",
    desc: "NOCFPS growth qtr over qtr",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "revenueGrowthOneYear",
    label: "Revenue growth 1 year",
    desc: "Revenue growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "revenueGrowthFiveYear",
    label: "Revenue growth 5 year",
    desc: "Revenue growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "totalAssetGrowthOneYear",
    label: "Total asset growth 1 year",
    desc: "Total asset growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "totalAssetGrowthFiveYear",
    label: "Total asset growth 5 year",
    desc: "Total asset growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "netIncomeGrowthOneYear",
    label: "Net income growth 1 year",
    desc: "Net income growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "netIncomeGrowthFiveYear",
    label: "Net income growth 5 year",
    desc: "Net income growth 5 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "totalLiabilitiesGrowthOneYear",
    label: "Total liabilities growth 1 year",
    desc: "Total liabilities growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "operatingProfitGrowthOneYear",
    label: "Operating profit growth 1 year",
    desc: "Operating profit growth 1 year",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "0;10", text: "Positive low (0-10%)" },
      { type: "default", value: "25;null", text: "High (over 25%)" },
      { type: "default", value: "null;5", text: "Under 5%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "null;15", text: "Under 15%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;25", text: "Under 25%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "5;null", text: "Over 5%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "15;null", text: "Over 15%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "25;null", text: "Over 25%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "directorShareHolding",
    label: "Director share",
    desc: "Director shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "govtShareHolding",
    label: "Government share",
    desc: "Government shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "publicShareHolding",
    label: "Public share",
    desc: "Public shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "foreignShareHolding",
    label: "Foreign share",
    desc: "Foreign shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "instituteShareHolding",
    label: "Institute share",
    desc: "Institute shareholding (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "freeFloatShare",
    label: "Free float share",
    desc: "Free float share (%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "0;50", text: "Low (under 50%)" },
      { type: "default", value: "50;null", text: "High (over 50%)" },
      { type: "default", value: "null;90", text: "Under 90%" },
      { type: "default", value: "null;80", text: "Under 80%" },
      { type: "default", value: "null;70", text: "Under 70%" },
      { type: "default", value: "null;60", text: "Under 60%" },
      { type: "default", value: "null;50", text: "Under 50%" },
      { type: "default", value: "null;40", text: "Under 40%" },
      { type: "default", value: "null;30", text: "Under 30%" },
      { type: "default", value: "null;20", text: "Under 20%" },
      { type: "default", value: "null;10", text: "Under 10%" },
      { type: "default", value: "10;null", text: "Over 10%" },
      { type: "default", value: "20;null", text: "Over 20%" },
      { type: "default", value: "30;null", text: "Over 30%" },
      { type: "default", value: "40;null", text: "Over 40%" },
      { type: "default", value: "50;null", text: "Over 50%" },
      { type: "default", value: "60;null", text: "Over 60%" },
      { type: "default", value: "70;null", text: "Over 70%" },
      { type: "default", value: "80;null", text: "Over 80%" },
      { type: "default", value: "90;null", text: "Over 90%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "directorShareHoldingChange",
    label: "Director share change",
    desc: "Director shareholding Change(%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Under -1%" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "1;null", text: "Over +1%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "instituteShareHoldingChange",
    label: "Institute share change",
    desc: "Institute shareholding Change(%)",
    unit: "%",
    suffix: "%",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Under -1%" },
      { type: "default", value: "null;-5", text: "Under -5%" },
      { type: "default", value: "null;-10", text: "Under -10%" },
      { type: "default", value: "null;-20", text: "Under -20%" },
      { type: "default", value: "1;null", text: "Over +1%" },
      { type: "default", value: "5;null", text: "Over +5%" },
      { type: "default", value: "10;null", text: "Over +10%" },
      { type: "default", value: "20;null", text: "Over +20%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "reserve",
    label: "Reserve Surplus",
    desc: "Reserve & Surplus",
    unit: "Crore",
    suffix: " cr",
    visible: 1,
    columnOrder: 100,
    options: [
      { type: "default", value: "100;null", text: "Over 100 Crore" },
      { type: "default", value: "200;null", text: "Over 200 Crore" },
      { type: "default", value: "500;null", text: "Over 500 Crore" },
      { type: "default", value: "1000;null", text: "Over 1000 Crore" },
      { type: "default", value: "2000;null", text: "Over 2000 Crore" },

      { type: "default", value: "null;100", text: "Under 100 Crore" },
      { type: "default", value: "null;200", text: "Under 200 Crore" },
      { type: "default", value: "null;500", text: "Under 500 Crore" },
      { type: "default", value: "null;1000", text: "Under 1000 Crore" },
      { type: "default", value: "null;2000", text: "Under 2000 Crore" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChange",
    label: "Price change (1D)",
    desc: "Price change (1 day)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 1002,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "5;null", text: "High (over 5%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-2", text: "Down -2%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-4", text: "Down -4%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-6", text: "Down -6%" },
      { type: "default", value: "null;-7", text: "Down -7%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-9", text: "Down -9%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "2;null", text: "Up 2%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "4;null", text: "Up 4%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "6;null", text: "Up 6%" },
      { type: "default", value: "7;null", text: "Up 7%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "9;null", text: "Up 9%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChangeOneWeek",
    label: "Price change (1W)",
    desc: "Price change (1 week)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "null;-15", text: "Down -15%" },
      { type: "default", value: "null;-20", text: "Down -20%" },
      { type: "default", value: "null;-30", text: "Down -30%" },
      { type: "default", value: "null;-50", text: "Down -50%" },
      { type: "default", value: "null;-100", text: "Down -100%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "default", value: "15;null", text: "Up 15%" },
      { type: "default", value: "20;null", text: "Up 20%" },
      { type: "default", value: "30;null", text: "Up 30%" },
      { type: "default", value: "50;null", text: "Up 50%" },
      { type: "default", value: "100;null", text: "Up 100%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChangeOneMonth",
    label: "Price change (1M)",
    desc: "Price change (1 month)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "null;-15", text: "Down -15%" },
      { type: "default", value: "null;-20", text: "Down -20%" },
      { type: "default", value: "null;-30", text: "Down -30%" },
      { type: "default", value: "null;-50", text: "Down -50%" },
      { type: "default", value: "null;-100", text: "Down -100%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "default", value: "15;null", text: "Up 15%" },
      { type: "default", value: "20;null", text: "Up 20%" },
      { type: "default", value: "30;null", text: "Up 30%" },
      { type: "default", value: "50;null", text: "Up 50%" },
      { type: "default", value: "100;null", text: "Up 100%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChangeSixMonth",
    label: "Price change (6M)",
    desc: "Price change (6 month)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "null;-15", text: "Down -15%" },
      { type: "default", value: "null;-20", text: "Down -20%" },
      { type: "default", value: "null;-30", text: "Down -30%" },
      { type: "default", value: "null;-50", text: "Down -50%" },
      { type: "default", value: "null;-100", text: "Down -100%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "default", value: "15;null", text: "Up 15%" },
      { type: "default", value: "20;null", text: "Up 20%" },
      { type: "default", value: "30;null", text: "Up 30%" },
      { type: "default", value: "50;null", text: "Up 50%" },
      { type: "default", value: "100;null", text: "Up 100%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChangeOneYear",
    label: "Price change (1Y)",
    desc: "Price change (1 year)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "null;-15", text: "Down -15%" },
      { type: "default", value: "null;-20", text: "Down -20%" },
      { type: "default", value: "null;-30", text: "Down -30%" },
      { type: "default", value: "null;-50", text: "Down -50%" },
      { type: "default", value: "null;-100", text: "Down -100%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "default", value: "15;null", text: "Up 15%" },
      { type: "default", value: "20;null", text: "Up 20%" },
      { type: "default", value: "30;null", text: "Up 30%" },
      { type: "default", value: "50;null", text: "Up 50%" },
      { type: "default", value: "100;null", text: "Up 100%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "pricePercentChangeFiveYear",
    label: "Price change (5Y)",
    desc: "Price change (5 year)",
    unit: "%",
    suffix: "%",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Down -1%" },
      { type: "default", value: "null;-3", text: "Down -3%" },
      { type: "default", value: "null;-5", text: "Down -5%" },
      { type: "default", value: "null;-8", text: "Down -8%" },
      { type: "default", value: "null;-10", text: "Down -10%" },
      { type: "default", value: "null;-15", text: "Down -15%" },
      { type: "default", value: "null;-20", text: "Down -20%" },
      { type: "default", value: "null;-30", text: "Down -30%" },
      { type: "default", value: "null;-50", text: "Down -50%" },
      { type: "default", value: "null;-100", text: "Down -100%" },
      { type: "default", value: "1;null", text: "Up 1%" },
      { type: "default", value: "3;null", text: "Up 3%" },
      { type: "default", value: "5;null", text: "Up 5%" },
      { type: "default", value: "8;null", text: "Up 8%" },
      { type: "default", value: "10;null", text: "Up 10%" },
      { type: "default", value: "15;null", text: "Up 15%" },
      { type: "default", value: "20;null", text: "Up 20%" },
      { type: "default", value: "30;null", text: "Up 30%" },
      { type: "default", value: "50;null", text: "Up 50%" },
      { type: "default", value: "100;null", text: "Up 100%" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "beta",
    label: "Beta (1 Year)",
    desc: "Beta (1 Year)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;0.5", text: "Under 0.5" },
      { type: "default", value: "null;1", text: "Under 1" },
      { type: "default", value: "null;1.5", text: "Under 1.5" },
      { type: "default", value: "null;2", text: "Under 2" },
      { type: "default", value: "null;2.5", text: "Under 2.5" },
      { type: "default", value: "null;3", text: "Under 3" },
      { type: "default", value: "null;3.5", text: "Under 3.5" },
      { type: "default", value: "null;4", text: "Under 4" },

      { type: "default", value: "0.5;null", text: "Over 0.5" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "1.5;null", text: "Over 1.5" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "2.5;null", text: "Over 2.5" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "3.5;null", text: "Over 3.5" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "sma20",
    label: "SMA (20)",
    desc: "SMA (20 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;sma20;gt", text: "Price above SMA20" },
      { type: "default", value: "ltp;sma20;lt", text: "Price below SMA20" },
      { type: "default", value: "ltp;sma20;eq", text: "Price same as SMA20" },
      { type: "default", value: "sma20;sma50;gt", text: "SMA20 above SMA50" },
      { type: "default", value: "sma20;sma50;lt", text: "SMA20 below SMA50" },
      { type: "default", value: "sma20;sma200;gt", text: "SMA20 above SMA200" },
      { type: "default", value: "sma20;sma200;lt", text: "SMA20 below SMA50" },
    ],
  },
  {
    name: "sma50",
    label: "SMA (50)",
    desc: "SMA (50 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;sma50;gt", text: "Price above SMA50" },
      { type: "default", value: "ltp;sma50;lt", text: "Price below SMA50" },
      { type: "default", value: "ltp;sma50;eq", text: "Price same as SMA50" },
      { type: "default", value: "sma50;sma20;gt", text: "SMA50 above SMA20" },
      { type: "default", value: "sma50;sma20;lt", text: "SMA50 below SMA20" },
      { type: "default", value: "sma50;sma200;gt", text: "SMA50 above SMA200" },
      { type: "default", value: "sma50;sma200;lt", text: "SMA50 below SMA200" },
    ],
  },
  {
    name: "sma200",
    label: "SMA (200)",
    desc: "SMA (200 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;sma200;gt", text: "Price above SMA200" },
      { type: "default", value: "ltp;sma200;lt", text: "Price below SMA200" },
      { type: "default", value: "ltp;sma200;eq", text: "Price same as SMA200" },
      { type: "default", value: "sma200;sma50;gt", text: "SMA200 above SMA50" },
      { type: "default", value: "sma200;sma50;lt", text: "SMA200 below SMA50" },
      { type: "default", value: "sma200;sma20;gt", text: "SMA200 above SMA20" },
      { type: "default", value: "sma200;sma20;lt", text: "SMA200 below SMA20" },
    ],
  },
  {
    name: "ema20",
    label: "EMA (20)",
    desc: "EMA (20 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;ema20;gt", text: "Price above EMA20" },
      { type: "default", value: "ltp;ema20;lt", text: "Price below EMA20" },
      { type: "default", value: "ltp;ema20;eq", text: "Price same as EMA20" },
      { type: "default", value: "ema20;ema50;gt", text: "EMA20 above EMA50" },
      { type: "default", value: "ema20;ema50;lt", text: "EMA20 below EMA50" },
      { type: "default", value: "ema20;ema200;gt", text: "EMA20 above EMA200" },
      { type: "default", value: "ema20;ema200;lt", text: "EMA20 below EMA50" },
    ],
  },
  {
    name: "ema50",
    label: "EMA (50)",
    desc: "EMA (50 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;ema50;gt", text: "Price above EMA50" },
      { type: "default", value: "ltp;ema50;lt", text: "Price below EMA50" },
      { type: "default", value: "ltp;ema50;eq", text: "Price same as EMA50" },
      { type: "default", value: "ema50;ema20;gt", text: "EMA50 above EMA20" },
      { type: "default", value: "ema50;ema20;lt", text: "EMA50 below EMA20" },
      { type: "default", value: "ema50;ema200;gt", text: "EMA50 above EMA200" },
      { type: "default", value: "ema50;ema200;lt", text: "EMA50 below EMA200" },
    ],
  },
  {
    name: "ema200",
    label: "EMA (200)",
    desc: "EMA (200 Day)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "ltp;ema200;gt", text: "Price above EMA200" },
      { type: "default", value: "ltp;ema200;lt", text: "Price below EMA200" },
      { type: "default", value: "ltp;ema200;eq", text: "Price same as EMA200" },
      { type: "default", value: "ema200;ema50;gt", text: "EMA200 above EMA50" },
      { type: "default", value: "ema200;ema50;lt", text: "EMA200 below EMA50" },
      { type: "default", value: "ema200;ema20;gt", text: "EMA200 above EMA20" },
      { type: "default", value: "ema200;ema20;lt", text: "EMA200 below EMA20" },
    ],
  },
  {
    name: "rsi",
    label: "RSI (14)",
    desc: "Relative Strength Index (14)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },
      { type: "default", value: "60;null", text: "Over 60" },
      { type: "default", value: "70;null", text: "Over 70" },
      { type: "default", value: "80;null", text: "Over 80" },
      { type: "default", value: "90;null", text: "Over 90" },
      { type: "default", value: "null;90", text: "Under 90" },
      { type: "default", value: "null;80", text: "Under 80" },
      { type: "default", value: "null;70", text: "Under 70" },
      { type: "default", value: "null;60", text: "Under 60" },
      { type: "default", value: "null;50", text: "Under 50" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "adx",
    label: "ADX (14)",
    desc: "Average Directional Index (14)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },
      { type: "default", value: "60;null", text: "Over 60" },
      { type: "default", value: "70;null", text: "Over 70" },
      { type: "default", value: "80;null", text: "Over 80" },
      { type: "default", value: "90;null", text: "Over 90" },
      { type: "default", value: "null;90", text: "Under 90" },
      { type: "default", value: "null;80", text: "Under 80" },
      { type: "default", value: "null;70", text: "Under 70" },
      { type: "default", value: "null;60", text: "Under 60" },
      { type: "default", value: "null;50", text: "Under 50" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "stoch",
    label: "Stochastic %K",
    desc: "Stochastic %K (14, 3, 3)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },
      { type: "default", value: "60;null", text: "Over 60" },
      { type: "default", value: "70;null", text: "Over 70" },
      { type: "default", value: "80;null", text: "Over 80" },
      { type: "default", value: "90;null", text: "Over 90" },
      { type: "default", value: "null;90", text: "Under 90" },
      { type: "default", value: "null;80", text: "Under 80" },
      { type: "default", value: "null;70", text: "Under 70" },
      { type: "default", value: "null;60", text: "Under 60" },
      { type: "default", value: "null;50", text: "Under 50" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "mfi",
    label: "MFI (10)",
    desc: "Money Flow Index (10)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "default", value: "20;null", text: "Over 20" },
      { type: "default", value: "30;null", text: "Over 30" },
      { type: "default", value: "40;null", text: "Over 40" },
      { type: "default", value: "50;null", text: "Over 50" },
      { type: "default", value: "60;null", text: "Over 60" },
      { type: "default", value: "70;null", text: "Over 70" },
      { type: "default", value: "80;null", text: "Over 80" },
      { type: "default", value: "90;null", text: "Over 90" },
      { type: "default", value: "null;90", text: "Under 90" },
      { type: "default", value: "null;80", text: "Under 80" },
      { type: "default", value: "null;70", text: "Under 70" },
      { type: "default", value: "null;60", text: "Under 60" },
      { type: "default", value: "null;50", text: "Under 50" },
      { type: "default", value: "null;40", text: "Under 40" },
      { type: "default", value: "null;30", text: "Under 30" },
      { type: "default", value: "null;20", text: "Under 20" },
      { type: "default", value: "null;10", text: "Under 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "macd",
    label: "MACD (12, 26)",
    desc: "MACD Level (12, 26)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      { type: "default", value: "null;-0.000001", text: "Negative (under 0%)" },
      { type: "default", value: "0.000001;null", text: "Positive (over 0%)" },
      { type: "default", value: "null;-1", text: "Under -1" },
      { type: "default", value: "null;-2", text: "Under -2" },
      { type: "default", value: "null;-3", text: "Under -3" },
      { type: "default", value: "null;-4", text: "Under -4" },
      { type: "default", value: "null;-5", text: "Under -5" },
      { type: "default", value: "null;-6", text: "Under -6" },
      { type: "default", value: "null;-7", text: "Under -7" },
      { type: "default", value: "null;-8", text: "Under -8" },
      { type: "default", value: "null;-9", text: "Under -9" },
      { type: "default", value: "null;-10", text: "Under -10" },
      { type: "default", value: "1;null", text: "Over 1" },
      { type: "default", value: "2;null", text: "Over 2" },
      { type: "default", value: "3;null", text: "Over 3" },
      { type: "default", value: "4;null", text: "Over 4" },
      { type: "default", value: "5;null", text: "Over 5" },
      { type: "default", value: "6;null", text: "Over 6" },
      { type: "default", value: "7;null", text: "Over 7" },
      { type: "default", value: "8;null", text: "Over 8" },
      { type: "default", value: "9;null", text: "Over 9" },
      { type: "default", value: "10;null", text: "Over 10" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "williamR",
    label: "Williams %R (14)",
    desc: "Williams Percent Range (14)",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 100,
    options: [
      // { type: "default", value: "-20;0", text: "Overbought" },
      // { type: "default", value: "-100;-80", text: "Oversold" },
      { type: "default", value: "-10;0", text: "Over -10" },
      { type: "default", value: "-20;0", text: "Over -20" },
      { type: "default", value: "-30;0", text: "Over -30" },
      { type: "default", value: "-40;0", text: "Over -40" },
      { type: "default", value: "-50;0", text: "Over -50" },
      { type: "default", value: "-60;0", text: "Over -60" },
      { type: "default", value: "-70;0", text: "Over -70" },
      { type: "default", value: "-80;0", text: "Over -80" },
      { type: "default", value: "-90;0", text: "Over -90" },
      { type: "default", value: "-100;0", text: "Over -100" },
      { type: "custom", value: "null;null", text: "Custom range" },
    ],
  },
  {
    name: "candlestick",
    label: "Candlestick",
    desc: "Candlestick",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 10,
    options: [
      { type: "default", value: "hammer", text: "Hammer" },
      { type: "default", value: "inverted_hammer", text: "Inverted Hammer" },

      { type: "default", value: "bullish_harami", text: "Bullish Harami" },
      { type: "default", value: "bearish_harami", text: "Bearish Harami" },

      {
        type: "default",
        value: "bullish_engulfing",
        text: "Bullish Engulfing",
      },
      {
        type: "default",
        value: "bearish_engulfing",
        text: "Bearish Engulfing",
      },

      { type: "default", value: "bullish_pin_bar", text: "Bullish Pin Bar" },
      { type: "default", value: "bearish_pin_bar", text: "Bearish Pin Bar" },
      { type: "default", value: "morning_star", text: "Morning Star" },
      { type: "default", value: "evening_star", text: "Evening Star" },
      { type: "default", value: "shooting_star", text: "Shooting Star" },
      {
        type: "default",
        value: "three_white_soldiers",
        text: "Three White Soldiers",
      },
      {
        type: "default",
        value: "three_black_crows",
        text: "Three Black Crows",
      },
      {
        type: "default",
        value: "three_inside_down",
        text: "Three Inside Down",
      },
      { type: "default", value: "three_outside_up", text: "Three Outside Up" },
      { type: "default", value: "tweezer_top", text: "Tweezer Top" },
      { type: "default", value: "tweezer_bottom", text: "Tweezer Bottom" },
      { type: "default", value: "bullish_marubozu", text: "Bullish Marubozu" },
      { type: "default", value: "bearish_marubozu", text: "Bearish Marubozu" },
      { type: "default", value: "dragonfly_doji", text: "Dragonfly Doji" },
      { type: "default", value: "gravestone_doji", text: "Gravestone Doji" },
      { type: "default", value: "dark_cloud_cover", text: "Dark Cloud Cover" },
      { type: "default", value: "hanging_man", text: "Hanging Man" },
      { type: "default", value: "mat_hold", text: "Mat Hold" },
      { type: "default", value: "spinning_top", text: "Spinning Top" },
      {
        type: "default",
        value: "falling_three_methods",
        text: "Falling Three Methods",
      },
      { type: "default", value: "piercing_line", text: "Piercing Line" },
      { type: "default", value: "dark_cloud_cover", text: "Dark Cloud Cover" },
    ],
  },
  {
    name: "patterns",
    label: "Pattern",
    desc: "Pattern",
    unit: "",
    visible: 1,
    placement: "technical",
    columnOrder: 10,
    options: [
      { type: "default", text: "Double top", value: "double_top" },
      { type: "default", text: "Double bottom", value: "double_bottom" },
      {
        type: "default",
        text: "Head and shoulders",
        value: "head_and_shoulders",
      },
      {
        type: "default",
        text: "Inverse head and shoulders",
        value: "inverse_head_and_shoulders",
      },
      { type: "default", text: "Channel up", value: "channel_up" },
      { type: "default", text: "Channel down", value: "channel_down" },
      {
        type: "default",
        text: "Triangle ascending",
        value: "ascending_triangle",
      },
      {
        type: "default",
        text: "Triangle descending",
        value: "descending_triangle",
      },
    ],
  },
];
